### ISSUE TITLE
很完美，就差一点点

### ISSUE THREAD

**Issue by atishoo** [pacifio/route_transitions#2]
ios跳转后，左滑返回就被禁用掉了，弄个参数让人动态控制一下最好了
安卓的很完美

**Comment by pacifio** [comment]
It's only an animation utility
If you want IOS styled left slide please use [CupertinoPageRoute](https://api.flutter.dev/flutter/cupertino/CupertinoPageRoute-class.html)

**Comment by atishoo** [comment]
thank you for your reply
